config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :listings do
    resources :orders, only: [:new, :create]
  end

  get 'pages/about'
  get 'pages/contact'
  get 'seller' => 'listings#seller'
  get 'sales' => 'orders#sales'
  get 'purchases' => 'orders#purchases'

  root 'listings#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base

	belongs_to :user
	has_many :orders

	has_attached_file :image, styles: { medium: "200x>", thumb: "100x100>" }, 
										default_url: "noImage.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates :name, :description, :price, presence: true
  validates :price, numericality: { greater_than: 0 }
  validates :image, attachment_presence: true

end

app/models/order.rb
class Order < ActiveRecord::Base

	belongs_to :listing
	belongs_to :buyer, class_name: 'User'
	belongs_to :seller, class_name: 'User'

	validates :address, :city, :state, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :listings, dependent: :destroy
	has_many :sales, class_name: 'Order', foreign_key: 'seller_id'
	has_many :purchases, class_name: 'Order', foreign_key: 'buyer_id'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :destroy, :seller]
  before_action :check_user, only: [:edit, :update, :destroy]

  def seller
    @listings = Listing.where(user: current_user).order('created_at DESC')
  end

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all.order('created_at DESC')
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id

    if current_user.recipient.blank?
      Stripe.api_key = ENV['STRIPE_API_KEY']
      token = params[:stripeToken]

      recipient = Stripe::Recipient.create(
        :name => current_user.name,
        :type => 'individual',
        :bank_account => token
        )
    end

    current_user.recipient = recipient.id
    current_user.save

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image)
    end

    def check_user
      if current_user != @listing.user
        redirect_to root_path, alert: 'Sorry, this listing belongs to someone else.'
      end
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def sales
    @orders = Order.all.where(seller: current_user).order('created_at DESC')
  end

  def purchases
    @orders = Order.all.where(buyer: current_user).order('created_at DESC')
  end

  # GET /orders/new
  def new
    @order = Order.new
    @listing = Listing.find(params[:listing_id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @listing = Listing.find(params[:listing_id])
    @seller = @listing.user

    @order.listing_id = @listing.id
    @order.buyer_id = current_user.id
    @order.seller_id = @seller.id

    Stripe.api_key = ENV['STRIPE_API_KEY']
    token = params[:stripeToken]

    begin
      charge = Stripe::Charge.create(
        :amount => (@listing.price * 100).floor,
        :currency => 'usd',
        :source => token
        )
      flash[:notice] = 'Thanks for ordering!'
    rescue Stripe::CardError => e
      flash[:danger] = e.message
    end

    transfer = Stripe::Transfer.create(
      :amount => (@listing.price * 95).floor,
      :currency => 'usd',
      :recipient => @seller.recipient
      )

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_path }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:address, :city, :state)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:div, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class='row'>
	<div class="col-md-12">
		<hr>
		<p>&copy; 2015</p>
	</div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <%= value %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'EtsyClone', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'About', pages_about_path %></li>
        <li><%= link_to 'Contact', pages_contact_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Seller Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Manage Listings', seller_path %></li>
            <li><%= link_to 'Sales History', sales_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Purchase History', purchases_path %></li>
            <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
            <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
          
        <% else %>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Log In', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EtsyClone</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://js.stripe.com/v2/' %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>
</head>
<body>

	<%= render 'layouts/navigation' %>

	<div class="container">

		<%= render 'layouts/messages' %>

		<%= yield %>

		<%= render 'layouts/footer' %>

	</div>

</body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing, html: { multipart: true }) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation" class='alert alert-danger alert-dismissable'>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="stripe_error" class="alert alert-danger alert-dismissible" role="alert" style="display:none">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <noscript>
      JavaScript is not enabled and is required for this form. Please enable it in your web browser settings.
    </noscript>
  </div>

  <div class="field form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <% if current_user.recipient.blank? %>
    <br>
    <h3>Bank Account Information</h3>
    <div class="form-group">
      <%= label_tag :country %>
      <%= text_field_tag :country, nil, { :name => nil, :'data-stripe' => 'country', class: 'form-control' } %>
    </div>
    <div class="form-group">
      <%= label_tag :routing_number %>
      <%= text_field_tag :routing_number, nil, { :name => nil, :'data-stripe' => 'routingNumber', class: 'form-control' } %>
    </div>
    <div class="form-group">
      <%= label_tag :account_number %>
      <%= text_field_tag :account_number, nil, { :name => nil, :'data-stripe' => 'accountNumber', class: 'form-control' } %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3>Edit Listing</h3>
			</div>

			<div class="panel-body">
				<%= render 'form' %>
			</div>

			<div class="panel-footer">
				<%= link_to 'Show', @listing, class: 'btn btn-link' %> |
				<%= link_to 'Back', listings_path, class: 'btn btn-link' %>
			</div>
		</div>
	</div>
</div>

app/views/listings/index.html.erb
<!-- <p id="notice"><%= notice %></p>-->

<div class="jumbotron text-center">
  <h1>Handcrafted items from<br>around the world.</h1>
  <h2>Discover one of a kind items.</h2>
</div>

 <div class="text-center">
  <div class="row">
    <% @listings.each do |listing| %>
      <div class="col-md-3">

        <div class="thumbnail">
          <%= link_to image_tag(listing.image.url), listing %>
          <div class="caption">
            <h3><%= listing.name %></h3>
            <p><%= number_to_currency(listing.price) %></p>
            <p><%= "Sold by #{listing.user.name}" %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: 'btn btn-link', data: { no_turbolink: true } %>
<% end %>

app/views/listings/new.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3>New Listing</h3>
			</div>

			<div class="panel-body">
				<%= render 'form' %>
			</div>

			<div class="panel-footer">
				<%= link_to 'Back', listings_path, class: 'btn btn-link' %>
			</div>
		</div>
	</div>
</div>

app/views/listings/seller.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<table class="table table-hover table-condensed table-striped table-bordered">
  <tr>
    <th class='text-center'>Image</th>
    <th class='text-center'>Name</th>
    <th class='text-center'>Description</th>
    <th class='text-center'>Price</th>
    <th class='text-center'>Actions</th>
  </tr>

  <% @listings.each do |listing| %>
    <tr>
      <td><%= link_to image_tag(listing.image.url(:thumb)), listing %></td>
      <td><%= listing.name %></td>
      <td><%= listing.description %></td>
      <td><%= number_to_currency(listing.price) %></td>
      <td>
        <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Action <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li><%= link_to 'View', listing, class: 'btn btn-link' %></li>
            <li><%= link_to 'Edit', edit_listing_path(listing), class: 'btn btn-link' %></li>
            <li><%= link_to 'Destroy', listing, class: 'btn btn-link', method: :delete, data: { confirm: 'Are you sure?' } %></li>
          </ul>
        </div>
      </td>
    </tr>
  <% end %>
</table>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: 'btn btn-link', data: { no_turbolink: true } %>
<% end %>

app/views/listings/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="row">
	<div class="col-md-6">
		<div class="thumbnail">
			<%= image_tag @listing.image.url %>
		</div>
	</div>
	<div class="col-md-6">
		<h3><%= @listing.name %></h3>
		<p><%= number_to_currency(@listing.price) %></p>
		<p><%= @listing.description %></p>
		<div class="text-center">
			<br>
			<%= link_to 'Buy It Now!', new_listing_order_path(@listing), class: 'btn btn-success btn-lg', data: { no_turbolink: true } %>
		</div>
	</div>
</div>

<% if (user_signed_in?) && (current_user == @listing.user) %>
	<%= link_to 'Edit', edit_listing_path(@listing), class: 'btn btn-link' %> |
<% end %>
<%= link_to 'Back', listings_path, class: 'btn btn-link' %>

app/views/orders/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="thumbnail">
      <%= image_tag @listing.image.url %>
    </div>
    <h3><%= @listing.name %></h3>
    <p><%= number_to_currency(@listing.price) %></p>
  </div>

  <div class="col-md-8">
    <%= form_for([@listing, @order]) do |f| %>
      <% if @order.errors.any? %>
        <div id="error_explanation" class='alert alert-danger alert-dismissable'>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h4>

          <ul>
          <% @order.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div id="stripe_error" class="alert alert-danger alert-dismissible" role="alert" style="display:none">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <noscript>
          JavaScript is not enabled and is required for this form. Please enable it in your web browser settings.
        </noscript>
      </div>

      <div class="field form-group">
        <%= f.label :address %><br>
        <%= f.text_field :address, class: 'form-control' %>
      </div>

      <div class="field form-group">
        <%= f.label :city %><br>
        <%= f.text_field :city, class: 'form-control' %>
      </div>

      <div class="field form-group">
        <%= f.label :state %><br>
        <%= f.text_field :state, class: 'form-control' %>
      </div>

      <div class="field form-group">
        <div class="row">

          <div class="col-md-8">
            <%= label_tag :card_number, 'Credit Card Number' %><br>
            <%= text_field_tag :card_number, nil, { :name => nil, :'data-stripe' => 'number', class: 'form-control' } %>
          </div>

          <div class="col-md-4">
            <%= label_tag :car_code, 'CVC' %><br>
            <%= text_field_tag :card_code, nil, { :name => nil, :'data-stripe' => 'cvc', class: 'form-control' } %>
          </div>

        </div>
      </div>

      <div class="field form-group">
        <%= label_tag nil, 'Expiration Date' %>
        <div class="row">
      
          <div class="col-md-3">
            <%= select_month nil, { use_two_digit_numbers: true }, { :name => nil, :'data-stripe' => 'exp-month', class: 'form-control' } %>
          </div>

          <div class="col-md-3">
            <%= select_year nil, { start_year: Date.today.year, end_year: Date.today.year + 15 }, { :name => nil, :'data-stripe' => 'exp-year', class: 'form-control' } %>
          </div>

        </div>
      </dvi>

      <br>

      <div class="actions">
        <%= f.submit 'Complete Order', class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/new.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="panel panel-default">

			<div class="panel-body">
				<%= render 'form' %>
			</div>

			<!-- <div class="panel-footer"> -->
				<%= link_to 'Back', listing_orders_path, class: 'btn btn-link' %>
			<!-- </div> -->
		</div>
	</div>
</div>

app/views/orders/purchases.html.erb
<div class="text-center">
  <h2>Your Purchase History</h2>
</div>

<table class="table table-hover table-condensed table-striped table-bordered">
  <tr>
    <th class='text-center'>Image</th>
    <th class='text-center'>Item</th>
    <th class='text-center'>Price</th>
    <th class='text-center'>Seller</th>
    <th class='text-center'>Date Purchased</th>
  </tr>

  <% @orders.each do |order| %>
    <tr>
      <td class='text-center'><%= image_tag order.listing.image.url(:thumb) %></td>
      <td class='text-center'><%= order.listing.name %></td>
      <td class='text-center'><%= number_to_currency(order.listing.price) %></td>
      <td class='text-center'><%= order.seller.name %></td>
      <td class='text-center'><%= order.created_at.strftime('%B %-d, %Y') %></td>
    </tr>
  <% end %>
</table>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: 'btn btn-link', data: { no_turbolink: true } %>
<% end %>

app/views/orders/sales.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="text-center">
  <h2>Your Sales History</h2>
</div>

<table class="table table-hover table-condensed table-striped table-bordered">
  <tr>
    <th class='text-center'>Image</th>
    <th class='text-center'>Item</th>
    <th class='text-center'>Price</th>
    <th class='text-center'>Customer</th>
    <th class='text-center'>Date Sold</th>
  </tr>

  <% @orders.each do |order| %>
    <tr>
      <td class='text-center'><%= image_tag order.listing.image.url(:thumb) %></td>
      <td class='text-center'><%= order.listing.name %></td>
      <td class='text-center'><%= number_to_currency(order.listing.price) %></td>
      <td class='text-center'><%= order.buyer.name %></td>
      <td class='text-center'><%= order.created_at.strftime('%B %-d, %Y') %></td>
    </tr>
  <% end %>
</table>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: 'btn btn-link', data: { no_turbolink: true } %>
<% end %>

app/views/pages/about.html.erb
<h1>Welcome to Etsy Clone</h1>
<h3>Etsy clone is an online marketplace for buying and selling handmade goods</h3>

app/views/pages/contact.html.erb
<h1>Email us at hello@etsyclone.com</h1>